services:
  - type: web
    name: yeshiva-system
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app:app"

databases:
  - name: yeshiva-db